APIDiff.swift: Address warning  by using task group instead of semaphore
swiftlang/swift-package-manager pull request #7959
Opened 2024-09-11 13:03 UTC by valeriyvan

2024-09-11 14:52 UTC, valeriyvan commented on Sources/Commands/PackageCommands/APIDiff.swift
> +            let results = ThreadSafeArrayStore<SwiftAPIDigester.ComparisonResult>()
done

2024-09-11 22:47 UTC, rauhul commented
Could we factor this into a more reusable component, like this?

[Sequence+ParallelMap.swift.txt](https://github.com/user-attachments/files/16971122/Sequence%2BParallelMap.swift.txt)

2024-09-12 05:29 UTC, valeriyvan commented
> Could we factor this into a more reusable component, like this?

Not in this PR. Open an issue if you think it does worth it.

2024-09-12 09:51 UTC, MaxDesiatov commented
You'll have to add `import _Concurrency` to the file you've changed to fix CMake builds and unblock CI.

2024-09-12 09:52 UTC, MaxDesiatov requested changes
You'll have to add import _Concurrency to the file you've changed to fix CMake builds and unblock CI.

2024-09-12 16:28 UTC, valeriyvan commented
> You'll have to add import _Concurrency to the file you've changed to fix CMake builds and unblock CI.

done

2024-09-12 16:31 UTC, MaxDesiatov commented
@swift-ci test

2024-09-12 17:44 UTC, MaxDesiatov commented
@swift-ci test windows

2024-09-12 17:45 UTC, MaxDesiatov approved these changes

2024-09-15 10:35 UTC, MaxDesiatov commented
@swift-ci test windows

2024-09-15 13:58 UTC, merged