Update CI triggers in CONTRIBUTING.md
swiftlang/swift-package-manager pull request #8187
Opened 2024-12-20 17:57 UTC by shahmishal

2024-12-20 17:58 UTC, shahmishal commented
@swift-ci test

2024-12-20 18:43 UTC, bkhouri requested changes

2024-12-20 18:43 UTC, bkhouri commented on CONTRIBUTING.md
> +@swift-ci please test self hosted
chore (blocking): The directives also appear to support `@swift-ci please test linux`, `@swift-ci please test windows`  and `@swift-ci please test macos`.  Can we include these directives in the documentation?

2025-01-03 18:58 UTC, plemarquand commented on CONTRIBUTING.md
> +@swift-ci please test self hosted
@bkhouri Mishal is out of office, I've addressed your comment

2025-01-13 20:21 UTC, edymtt commented
@swift-ci test

2025-01-13 20:25 UTC, bkhouri approved these changes

2025-01-16 23:08 UTC, edymtt commented
@swift-ci please test Linux

2025-01-17 05:36 UTC, merged